### ISSUE TITLE
Add new job postings

### ISSUE THREAD

**Issue by JessicaJackson** [ekumenlabs/ekumenlabs.github.io#102]
After saving & removing the previous job postings, please add the following so they appear on the /jobs page in the following order:

People Manager
Semi-Senior and Senior Developers for Robotics
Developer for Robotics

New URLs:
/peoplemanager
/senior
/junior

Page text:
People Manager - https://docs.google.com/document/d/1VMxD4xbdpB7hOKw-4eV0XNeO8Nqw6v-wtJYT0UVpNoE/edit#heading=h.a0dhj56zsciw
Semi-Senior and Senior Developers for Robotics https://docs.google.com/document/d/1RNlE-FA5AleNZcCW6NNPGnHncIOXsb8rZ_ABdvgbIng/edit
Junior Developer -
 https://docs.google.com/document/d/1J4wif1O0UD4Mkwi2NcwVW91X8se90vD1VO67mOsCSeM/edit#

**Comment by german-e-mas** [comment]
Previous job posts end with the following:

> We will for sure also consider candidates that don't have experience with these particular technologies but are eager to learn them. We take into account software development experience, growth potential and cultural match for our candidates. We’re a friendly, fun-loving bunch and expect the same from you!
>
> If you'd like to join Ekumen, send us an email to jobs@ekumenlabs.com. Tell us a bit about yourself, why you're interested in the position, and don’t forget to include a CV in English!
>
> This position is open to working in Ekumen's Buenos Aires office or remotely

@JessicaJackson , Should the new posts have the same text?

**Comment by basicNew** [comment]
Maybe we can put that in the "Jobs" page instead of having it on every job? Like:

> If you don't feel any of the job openings describe you or that you don't have experience with the required technologies but are eager to learn them, feel free to drop us a line. We take into account software development experience, growth potential and cultural match for our candidates. We’re a friendly, fun-loving bunch and expect the same from you!
> 
> ....

**Comment by basicNew** [comment]
Scratch that, that is already there :/

**Comment by JessicaJackson** [comment]
Yes, German, please include that information, and thank you for asking.

**Comment by JessicaJackson** [comment]
Yes, German, please include that information, and thank you for asking.



Jessica

--
Jessica Jackson
*Manager*

AR: +54 (11) 5219-0895
US: +1 (408) 757-0064

**Comment by german-e-mas** [comment]
Merged and deployed! You can see the new job posts here: [http://www.ekumenlabs.com/jobs/](http://www.ekumenlabs.com/jobs/)
