### ISSUE TITLE
Fix bios' text boxes

### ISSUE THREAD

**Issue by gecofernando** [ekumenlabs/ekumenlabs.github.io#103]
Some text is 'dripping' under the pictures:
![screen shot 2017-10-24 at 15 27 41](https://user-images.githubusercontent.com/9336889/31961088-1a25aeae-b8d0-11e7-9ee1-e53395eb3168.png)
![screen shot 2017-10-24 at 15 27 29](https://user-images.githubusercontent.com/9336889/31961089-1a444f94-b8d0-11e7-8a18-057502646c38.png)

**Comment by german-e-mas** [comment]
Interesting! Nice catch @gecofernando, thanks!

It happens when the width is too small.

![scrn](https://user-images.githubusercontent.com/14120807/31961310-bdf302b6-b8d0-11e7-94ab-412cc5c19c1d.png)

I'll prevent the text from jumping below the picture.

**Comment by german-e-mas** [comment]
Changes merged and deployed.
