### ISSUE TITLE
Fix Julian's Bio

### ISSUE THREAD

**Issue by julianmateu** [ekumenlabs/ekumenlabs.github.io#105]
Julian is under the "advisors" section in the Team page, but the text says he is the CEO. I think that's a little confusing.

**Comment by german-e-mas** [comment]
It was changed to read "former CEO" to avoid the confusion.

**Comment by basicNew** [comment]
yes, but maybe the wording it too subtle. Maybe we should come up with a better text.

**Comment by JessicaJackson** [comment]
It's what he was, so I would leave it.


Thanks!

Jessica

--
Jessica Jackson
*Manager*

AR: +54 (11) 5219-0895
US: +1 (408) 757-0064

**Comment by gecofernando** [comment]
Maybe add a clarification?
"Julian is the founder and former CEO of Ekumen. Nowadays he's focusing on
new projects but he's still working closely as an advisor."

**Comment by german-e-mas** [comment]
@adamantivm , this was changed when you were on vacations. Do you want to modify your bio? http://www.ekumenlabs.com/team/

**Comment by adamantivm** [comment]
I'm happy with what's there now. Thanks Ger!

**Comment by german-e-mas** [comment]
Thank you @adamantivm  . Closing this issue.
