### ISSUE TITLE
Fix Moire effect in Emi's picture

### ISSUE THREAD

**Issue by julianmateu** [ekumenlabs/ekumenlabs.github.io#106]
Emi's picture shows a moire pattern. I think this could be fixed with some photoshop. @gecofernando ?

![moire](https://user-images.githubusercontent.com/8532334/32058314-0b877dc0-ba40-11e7-9ee5-0fe66e1debdd.jpg)

Here are some possibly-useful links:
- https://www.slrlounge.com/what-causes-moire-how-to-avoid-it-how-to-remove-it/
- https://www.thoughtco.com/remove-moire-patterns-from-scanned-photos-1700238
- https://photographylife.com/how-to-remove-moire-in-photoshop

**Comment by gecofernando** [comment]
![emi-thumbnail](https://user-images.githubusercontent.com/9336889/32244986-16516668-be59-11e7-8adf-d6afce03b856.jpg)

**Comment by german-e-mas** [comment]
Thanks for the magic @gecofernando !

**Comment by german-e-mas** [comment]
Changes merged and deployed. You can now see Emi without the Moiré pattern in the website.
