### ISSUE TITLE
Add link to ROSCon link to Juan's team profile

### ISSUE THREAD

**Issue by JessicaJackson** [ekumenlabs/ekumenlabs.github.io#117]
"He enjoys learning and combining new technologies when working in a project. Recently Juan presented [How to Build Android Robots](https://vimeo.com/236191759) at ROSCon 2017"

**Comment by basicNew** [comment]
My 0.00002cts "recently" will be quickly outdated, maybe word it differently?

**Comment by german-e-mas** [comment]
+1 on the update. I think if we remove the "recently", the sentence still works great. What do you think @JessicaJackson ?

> Juan is an Electronics Engineer from the Instituto Tecnológico de Buenos Aires. When it comes to software development, he can build code for a wide variety of devices, from low-level hardware drivers for microcontrollers to applications in larger computer systems. He enjoys learning and combining new technologies when working in a project. Juan presented How to Build Android Robots at ROSCon 2017.
> 
> He spends most of his free time with his friends. He also likes playing paddle tennis, training at the gym, and watching a good movie.

**Comment by JessicaJackson** [comment]
Excellent point! +1. It's a link though, right?


Thanks!

Jessica

--
Jessica Jackson
*Manager*

AR: +54 (11) 5219-0895
US: +1 (408) 757-0064

**Comment by german-e-mas** [comment]
Not here, but it will be on the site. Thanks @JessicaJackson !

**Comment by german-e-mas** [comment]
Merged and deployed.
