### ISSUE TITLE
Remove job postings

### ISSUE THREAD

**Issue by basicNew** [ekumenlabs/ekumenlabs.github.io#119]
We are no longer hiring so we should remove the following entries:

- People Manager
- Semi-Senior and Senior Developers for Robotics
- Junior Developer for Robotics

**Comment by JessicaJackson** [comment]
Please archive them like last time, too.

**Comment by german-e-mas** [comment]
Merged and deployed. The job posts are inside https://drive.google.com/open?id=0B5QpINXMNER1WnJQbkpUQklPMUE. I commented that they were taken off the website today.
