### ISSUE TITLE
Add Lea's Bio

### ISSUE THREAD

**Issue by german-e-mas** [ekumenlabs/ekumenlabs.github.io#121]
We need to include @leandromo 's bio in the team.

fyi @gecofernando , you can place the text and thumbnail here when it's ready.

**Comment by leandromo** [comment]
Yes Ger!

We have finished with my bio yesterday (Jess helped me). So we going to
send you the valuable information today

**Comment by gecofernando** [comment]
Text: 

Leandro studied gastronomy and worked for several years in the field. He is currently studying for a degree in physical education and teaches classes in functional training and artistic gymnastics. At Ekumen he helps keep the office running smoothly. 
Leandro is very active and enjoys sports; he practices cheerleading, and also loves tennis, swimming and playing pool.

@ernestmc do you think we can do a photoshoot soon? (I'm guessing either tomorrow or when you come back from your trip).

**Comment by ernestmc** [comment]
Ok. I'll bring my camera tomorrow.

**Comment by german-e-mas** [comment]
Any update on the picture @gecofernando ?

**Comment by gecofernando** [comment]
![lea-thumbnail](https://user-images.githubusercontent.com/9336889/36042305-28927b50-0daa-11e8-890f-448dd336bcdb.jpg)

**Comment by german-e-mas** [comment]
Changes deployed. Closing this. Thanks everyone for your input!
