### ISSUE TITLE
Add FabriB's Bio 

### ISSUE THREAD

**Issue by gecofernando** [ekumenlabs/ekumenlabs.github.io#126]
After ~3 months of his start.
Pending text.
![fabrib-thumbnail](https://user-images.githubusercontent.com/9336889/36042494-ca744f02-0daa-11e8-8554-721fbfb83dfa.jpg)

**Comment by JessicaJackson** [comment]
Fabricio is an electronic engineer from the University of Buenos Aires. He is also a teaching assistant for the microcontroller laboratory at UBA where he teaches 8-bit microcontrollers to electronic and software engineering students. 
He has experience with robotics, programming in ASM, C, C++, Python, Matlab, signal processing, and biomedical engineering.
Fabricio is passionate about science and technology and believes they are the keys to the future.

**Comment by german-e-mas** [comment]
Merged and deployed!
