### ISSUE TITLE
Make a list of stubbed or missing content 

### ISSUE THREAD

**Issue by adamantivm** [ekumenlabs/ekumenlabs.github.io#13]
Thoroughly go through the Website and list here all the places where content is stubbed or copy/pasted and needs to be updated to include the final version.

Stubs:
- [x] Jobs listings includes copy/paste of ad
- [x] Projects has a bad copy of the Immedia project
- [ ] Team page has Ivan picture copied for Andres
- [ ] Home page content copy (text and images) is only example to be replaced

**Comment by sanbor** [comment]
Yesterday I updated this list adding the projects section and removing Javi and Fer from the team page.

**Comment by JessicaJackson** [comment]
Aged out
