### ISSUE TITLE
Configure HTTPS

### ISSUE THREAD

**Issue by german-e-mas** [ekumenlabs/ekumenlabs.github.io#134]
See: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ and https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by german-e-mas** [comment]
Done. The website now works with https.

**Comment by manzato** [comment]
![image](https://user-images.githubusercontent.com/572793/40249777-6d4f44ce-5aaa-11e8-8a65-a60b95ecd3f2.png)

**Comment by manzato** [comment]
the non "www." alternative doesn't work

**Comment by german-e-mas** [comment]
Interesting. I'll take a look. Thanks @manzato !

**Comment by german-e-mas** [comment]
@manzato , @adamantivm or @gecofernando , do you know who is the DNS provider for the `ekumenlabs` domain? We can set the non www alternative in it.

**Comment by manzato** [comment]
it is provided by dotster.com, I wouldn't know which record to add/modify... the access to that is in the "Users y passwords" doc (do you have access to it @german-e-mas ? )

**Comment by german-e-mas** [comment]
Thank you @manzato ! The modifications worked. I can now `wget` the following addresses without any issue.
```
wget http://ekumenlabs.com
wget http://www.ekumenlabs.com
wget https://ekumenlabs.com
wget https://www.ekumenlabs.com
```
They all connect to [https://www.ekumenlabs.com](https://www.ekumenlabs.com) without any kind of certificate issues (previously, `wget https://ekumenlabs.com` was failing).

Handy manual test below:

[http://www.ekumenlabs.com](http://www.ekumenlabs.com)
[http://ekumenlabs.com](http://ekumenlabs.com)
[https://www.ekumenlabs.com](https://www.ekumenlabs.com)
[https://ekumenlabs.com](https://ekumenlabs.com)

Closing this one. Hope there are no further issues.
