### ISSUE TITLE
Fix typo in Jimi's bio

### ISSUE THREAD

**Issue by julianmateu** [ekumenlabs/ekumenlabs.github.io#136]
Current text is: 

> Julian is on his final year of the Masters of Science Degree in Electrical Engineering at the University > of Buenos Aires. He is also a teaching assistant in a Modern Physics Course.
> 
> He enjoys learning and reading about new things every day, and has curiosity and interest in science and technology in general. He applies his knowledge of math and algorithms working with Project Tango and developing Android applications, and he is learning along the way.
> 
> He also studies musical composition and plays the piano and the guitar. In his free time he loves gathering with friends, playing and listening to music, watching movies **an** reading books.

The last sentence should be "and" reading books. Also, I propose an update to the first two paragraphs given that I finished my degree and Tango was re-branded to ARCore. Full text should be:

> Julian finished his Masters of Science Degree in Electrical Engineering at the University of Buenos Aires. He is also a teaching assistant in a Classical Physics Course.
> 
> He enjoys learning and reading about new things every day, and has curiosity and interest in science and technology in general. He applies his knowledge of math and algorithms working with ARCore and developing AR applications, and he is learning along the way.
> 
> He also studies musical composition and plays the piano and the guitar. In his free time he loves gathering with friends, playing and listening to music, watching movies and reading books.

**Comment by german-e-mas** [comment]
Merged and deployed!
