### ISSUE TITLE
Publish 2 new job ads

### ISSUE THREAD

**Issue by JessicaJackson** [ekumenlabs/ekumenlabs.github.io#137]
These will link of the jobs page per usual and you can reuse images:

https://docs.google.com/document/d/1Jz6cmgZAWXzJu9oaF4OAAOs-nZatdnJtEwpreQGpgkQ/edit?ts=5af9937e#
https://docs.google.com/document/d/1vuifPxqw6nDrEPUYFwUy7qGW2FOjXzBjaoN1cKCe_fc/edit?ts=5af980a5#

**Comment by german-e-mas** [comment]
PR #139 is now merged and deployed. The job ads are online.
