### ISSUE TITLE
Project tags - footer position

### ISSUE THREAD

**Issue by german-e-mas** [ekumenlabs/ekumenlabs.github.io#150]
When clicking on a project tag, the footer is not in the bottom of the screen.

![www ekumenlabs com_projects_tags_service-robots html](https://user-images.githubusercontent.com/14120807/41417449-c564870e-6fc3-11e8-8372-23f51f9ceb73.png)

It should be on the bottom of the screen.

**Comment by tul1** [comment]
I found a way to solve this problem, however it's a bit dirty and it might need further investigation on how middleman renders.

![image](https://user-images.githubusercontent.com/10169300/41488384-84dece92-70c2-11e8-8769-2a1044891d35.png)
