### ISSUE TITLE
Projects to a grid

### ISSUE THREAD

**Issue by tul1** [ekumenlabs/ekumenlabs.github.io#151]
Try render projects into a grid to check how it looks.

**Comment by tul1** [comment]
@german-e-mas is there any news about this?

**Comment by tul1** [comment]
@gecofernando what do you think about this layout for the projects section?

![0 0 0 0_4567_projects_ 1](https://user-images.githubusercontent.com/10169300/42040756-bcefccba-7ac6-11e8-824c-db5c7f18e5bc.png)

**Comment by gecofernando** [comment]
Looks *way* better than before!

I'd define a fix size for each 'square'. And color the background when hovering, if it's not done already.

Lastly I think it'd be good if the text showing is a super short description of the project instead of the long text a randomly cut at some point.

**Comment by tul1** [comment]
Update: after talking the previous subjects with @gecofernando offline I adjust several details. And the result is shown in the image in attached beneath:

![0 0 0 0_4567_projects_ 3](https://user-images.githubusercontent.com/10169300/42053440-eb521b28-7ae7-11e8-80ae-4ba1e64c2819.png)

@gecofernando what do you think now?

**Comment by gecofernando** [comment]
Awesome!
I think You'll have to remove the justified text from the titles as it's
making a mess.



Fernando Kopelman
  Office Manager

**Comment by german-e-mas** [comment]
Last image looks good @tul1 . Thanks for the comments @gecofernando !

**Comment by tul1** [comment]
this issue was related to the following PR:
https://github.com/ekumenlabs/ekumenlabs.github.io/pull/155
