### ISSUE TITLE
Responsive view of Team not working properly

### ISSUE THREAD

**Issue by tul1** [ekumenlabs/ekumenlabs.github.io#152]
Team rendering view isn't responding well smaller viewports.
![image](https://user-images.githubusercontent.com/10169300/41418379-f1ef8fec-6fc5-11e8-8b1f-840bd7b2e9ab.png)

**Comment by tul1** [comment]
We have three different scenarios here.
- First the one shown in the previous message in Pato's profile where the first name starts on top but the last name is rendered below the photo because it's to long. 
- Second case it's when the first name and last name have the proper size to be rendered next to the photo. This is the most compact scenario. the profile below shows that  case:
![image](https://user-images.githubusercontent.com/10169300/41419221-e187bec0-6fc7-11e8-812b-f76c5f0a16fa.png)
-Finally, the case when the first and last name are too long to be rendered next to the profile's photography, such as in the image below.
![image](https://user-images.githubusercontent.com/10169300/41419094-8b0236f2-6fc7-11e8-9108-6e47f6bbc934.png)

I believe that the first scenario isn't right and we definitely don't want to show profiles that way. Secondly we need to choose between the scenario two and three. Personally, I like the compacter option, the second scenario, where the first and second name fit next to the photo. Showing the name below the profile's photography and below that the more text looks unstructured to me.

In order to implement the second scenario I suggest to reduce the name size as a possible solution.

What do you think @german-e-mas ? What path do you think I should take?

**Comment by german-e-mas** [comment]
I agree, the compact version looks nicer. You can modify either the font size or the image's dimensions for smaller viewports. I'd suggest to try this one.

If the name length still causes issues, I think we can change the layout a little for smaller viewports, and have the name on the top. Something like this:

```
  +----------------------+
  |Name                  |
  +----------------------+
  |Picture   |Text       |
  |          |..         |
  |          |..         |
  |          |..         |
  |          |..         |
  +----------+..         |
  |Text continues here   |
  |                      |
  |                      |
  +----------------------+
```

**Comment by tul1** [comment]
Seems that the name is always to be an issue because even if we make it fit now maybe in the future a new employee could have super long name and that beyond our control. Having said that, let me tell you that I tried to fix it changing font-size and the picture's right margin but I didn't achieved an homogeneous result that works for every profile in the same way.
So, I'll go trying with a new layout.

**Comment by tul1** [comment]
This is the best I could obtain moving the several sizes to rem instead of pixels. But, changing the device the issue shows up again.

![0 0 0 0_4567_team_ galaxy s5](https://user-images.githubusercontent.com/10169300/41427060-187e9eda-6fdc-11e8-868e-fe67edfc468b.png)

Certainly to solve this matter we should change the layout for smaller viewport size.

**Comment by tul1** [comment]
I pushed a version including bootstrap flexbox and unfortunately it isn't working. It doesn't respond at all and I believe that is because flexbox isn't available for the project's bootstrap version (3.3.3). So, here we have to decide whether we chose to keep the name duplicated in the code switching its visibility for different viewports or to continue trying with flexbox but now implement it through scss.
@german-e-mas what do you think what path should we take?
The last version is available in the same PR I mentioned some comments before.

**Comment by german-e-mas** [comment]
I'd try with a CSS flexbox approach. Worst case scenario, we keep the duplicated name. Take into account that all the team files should have the same structure, not only those with large names.

**Comment by tul1** [comment]
I agree with you completely @german-e-mas . I'll give it a try then.
