### ISSUE TITLE
Try lighter gray

### ISSUE THREAD

**Issue by tul1** [ekumenlabs/ekumenlabs.github.io#163]
Try lighter gray for the project hover.

**Comment by gecofernando** [comment]
Bear in mind the gray is the same used in all the website. In case of using
a lighter gray (with which I agree) it should be changes everywhere.


Fernando Kopelman
  Office Manager

**Comment by tul1** [comment]
I've lighten the gray. What do you think @gecofernando ?

![image](https://user-images.githubusercontent.com/10169300/42106898-f5dfce68-7bab-11e8-9dcb-6244945fedec.png)

**Comment by gecofernando** [comment]
Looks good. Lets see how it works agains the dark purple!


Fernando Kopelman
  Office Manager
