### ISSUE TITLE
Remove scroll down button 

### ISSUE THREAD

**Issue by tul1** [ekumenlabs/ekumenlabs.github.io#165]
Remove scroll down button from the home page.

**Comment by german-e-mas** [comment]
PR Merged. Deploy pending.

**Comment by tul1** [comment]
this issue has been merged to middleman. Can I close it? @german-e-mas

**Comment by tul1** [comment]
This issue was related to the following PR:
https://github.com/ekumenlabs/ekumenlabs.github.io/pull/167
