### ISSUE TITLE
Thumbnail pop up

### ISSUE THREAD

**Issue by tul1** [ekumenlabs/ekumenlabs.github.io#166]
After a design and functionality talk with @gecofernando we concluded that the modal that pops up should be modify in the following way:

Functionality: 
+ Darken background when the modal pops up.
+ Close the modal when the user clicks outside the modal or scroll the web side.

Design:
+ Remove rounded corners.
+ Remove Close button.
+ Use Material design drop shadow for the text.
+ Set the image that is already in the modal as a header and overlap the title in white as it's done in the home page.
+ Move tags to the modal's bottom and align them as in the home page.
+ Add a Next and Previous button to jump from modals.

**Comment by german-e-mas** [comment]
I would suggest not to use a modal and explore a different layout. We could display this information directly on the homepage, without having users click things. What do you think about this approach @gecofernando ?

I was thinking of something like the image below. Having the thumbnail image to the left and text+tags to the right. Don't take this layout seriously, as it was done quickly by copy/pasting elements in the website and moving them around.

Each thumbnail should have an horizontal section.

<img src="https://user-images.githubusercontent.com/14120807/42104218-24fe03e0-7ba2-11e8-8774-962622e2182d.png" height="400" />

**Comment by gecofernando** [comment]
Design-wise I like the home page to be cleaner and with less text. I'd
rather have the four images side by side (note: I'd make them bigger,
reduce padding around, check the shape and drop shadow to match the rest
and definitely change the pictures) with a small text en top and no modal
popup, than all the text there all the time.

I believe the home page should allow to have a *quick and simple* overview
of what Ekumen is and does. This is the place for images, movement, flashy
things and less text.


Fernando Kopelman
  Office Manager

**Comment by tul1** [comment]
this task was related to the following PR:
https://github.com/ekumenlabs/ekumenlabs.github.io/pull/168
