### ISSUE TITLE
[experimental] Lateral arrows to pop next modal

### ISSUE THREAD

**Issue by tul1** [ekumenlabs/ekumenlabs.github.io#169]
This was spoken offline with @gecofernando and the idea is to add to the modal 2 arrows at its laterals. The arrow would work like a buttons and when the user clicks it the opened modal is replaced for a another.

**Comment by german-e-mas** [comment]
After seeing the issue with the modal on a mobile device, I'm _very_ skeptical about this.

**Comment by german-e-mas** [comment]
Closing this. Arrows won't work on mobile.
