### ISSUE TITLE
[Responsive] homepage subtitle text

### ISSUE THREAD

**Issue by tul1** [ekumenlabs/ekumenlabs.github.io#171]
The homepage's text "We’d like to help you solve hard [...]" in a mobile screen looks a little large and takes up a big portion of the screen. That we remarked @JessicaJackson yesterday. We can shrink it a little by reducing its font size as you've done with the team members' name. What do you think @german-e-mas ?

![image](https://user-images.githubusercontent.com/10169300/42336754-04b440d2-805b-11e8-94da-b4b960e9888f.png)

**Comment by german-e-mas** [comment]
Sure, shrink it down on mobile devices. It looks way larger than the logos, for example. Aim for a consistent view.

**Comment by tul1** [comment]
@german-e-mas what do you think about this size:

![image](https://user-images.githubusercontent.com/10169300/42589588-e1a015d2-8517-11e8-94d5-18af20d12402.png)

Another alternative would be to remove the subtitle for smartphone viewports.

**Comment by gecofernando** [comment]
IMHO the title should be smaller to avoid the piling up. The secondary
titles should be also smaller, not much bigger than the actual text. The
difference in color and alignment differentiates them enough.


Fernando Kopelman
  Office Manager

**Comment by tul1** [comment]
@gecofernando what we've talked with @german-e-mas offline is that we might remove that text when the screen is small, because in a smaller view it doesn't add any asset to the user experience. In the contrary, it pills up more meaning less text to the screen and prevents to show what's really important.

@gecofernando what do you think?

**Comment by tul1** [comment]
That's how it'd look:

![0 0 0 0_4567_ galaxy s5](https://user-images.githubusercontent.com/10169300/42834781-fec278c0-89cd-11e8-8a08-13654603b131.png)

**Comment by gecofernando** [comment]
Looks good. I think the text could be even a bit smaller.


Fernando Kopelman
  Office Manager

**Comment by tul1** [comment]
yes, it can be done, however, if the font size is too small it gets really difficult to read in a cellphone.
