### ISSUE TITLE
[Responsive] Closing modal

### ISSUE THREAD

**Issue by tul1** [ekumenlabs/ekumenlabs.github.io#172]
In the mobile view the modal takes up a large portion of the screen and in order to close it the user have to click on the small portion that the modal doesn't cover.
So, in this case we should come up with a closing mechanism such as a close button somewhere or close the modal when the user clicks anywhere on the screen. @german-e-mas do you have any position on this subject?

![image](https://user-images.githubusercontent.com/10169300/42338815-6ea901d4-8061-11e8-81b5-a973fd59dbe9.png)

**Comment by german-e-mas** [comment]
This has a higher priority: Users can get stuck!

There should be an obvious close button in the upper right part of the modal. It might be an inconvenience with the header and image though.

Potential other solution: Close button (or label) at the bottom of the modal, only for mobile views. The modal should be "longer" to ensure the users can see the button/label in the bottom of it. I don't think it looks good though (and the quick edited image looks awful). Examples of this:

| Mock1 | Mock2 |
| --- | --- |
| ![mock002](https://user-images.githubusercontent.com/14120807/42342501-a8318c72-806c-11e8-9ae8-b71172504775.png) | ![mock001](https://user-images.githubusercontent.com/14120807/42342503-a855b106-806c-11e8-9a25-930f65c950fe.png) |

The readability of the text and the image together is another issue.

**Comment by german-e-mas** [comment]
Just in case, try this on a real device, by either dev tools or your own cellphone (same network and your machine IP : 4567)
