### ISSUE TITLE
Migrate Google Apps domain

### ISSUE THREAD

**Issue by adamantivm** [ekumenlabs/ekumenlabs.github.io#18]
Related to #8

**Comment by sanbor** [comment]
The easiest way to do this would be to just create aliases to `ekumenlabs.com` website. Internally we would have to keep using our Google apps accounts with `creativa77.com.ar`.

If we want to use `ekumenlabs.com` to login into our Google apps accounts, we would have to transfer the email addresses to `ekumenlabs.com` and then create all the `creativa77.com.ar` aliases. This last approach is more complicated but we in future we can forget about `creativa77.com.ar`.

Here is all the info https://support.google.com/a/answer/54819?hl=en

**Comment by manzato** [comment]
What happened was that the revalidation of the domain seemed to be very cumbersome, but in the end, it was simply a matter of clicking a few buttons. So creativa77.com.ar is still under the Creativa SRL user. It is valid till 2015-10-17.

I would like at that point (expiration) to drop the domain if we can.

**Comment by german-e-mas** [comment]
Given the age, it is most likely that this issue has been resolved. Still, after reading the comments, I'd like to know the current state of this. We haven't dropped `@creativa77.com.ar` and we have `@ekumenlabs.com` set as an alias of it, is that correct, @manzato , @adamantivm ?

**Comment by adamantivm** [comment]
That's correct

**Comment by german-e-mas** [comment]
Thanks for the reply @adamantivm ! I will close this issue then.
