### ISSUE TITLE
Create institutional Skype account to add to the website

### ISSUE THREAD

**Issue by sanbor** [ekumenlabs/ekumenlabs.github.io#23]
Create an Skype account to add another communication channel in the website.
- [ ] Create Skype account
- [ ] Add credit
- [ ] [Associate Skype account with the Skype number](https://support.skype.com/en/faq/FA10531/how-do-i-set-up-a-skype-number-as-a-member-s-caller-id-in-skype-manager).
- [ ] Add the skype id to the website.

**Comment by german-e-mas** [comment]
@gecofernando The skype number is the one next to the contact. Do we want the Skype ID there as well?

**Comment by gecofernando** [comment]
Indeed the US number is an Skype number. It was updated recently.

**Comment by german-e-mas** [comment]
Thank you @gecofernando . Just to confirm: Do we want/need a "contact with Skype" link or something like that? Or just showing the number will do?

In case there's no link required, we can close this issue.

**Comment by gecofernando** [comment]
I think the email and phone number is more than enough.
Thanks Ger!

**Comment by german-e-mas** [comment]
Excellent. Closing this one then. Thanks @gecofernando !
