### ISSUE TITLE
Link to LinkedIn in Web page footer

### ISSUE THREAD

**Issue by adamantivm** [ekumenlabs/ekumenlabs.github.io#49]

**Comment by german-e-mas** [comment]
I don't see a LinkedIn link in the footer.
@gecofernando Can you give me the link of Ekumen's LinkedIn in order to include it?

**Comment by adamantivm** [comment]
https://www.linkedin.com/company/10215066/

**Comment by german-e-mas** [comment]
Merged and deployed. Closing this issue!
