### ISSUE TITLE
Create Twitter and G+ accounts.

### ISSUE THREAD

**Issue by sanbor** [ekumenlabs/ekumenlabs.github.io#6]
Should we just rename Creativa77 FB account to Ekumen when we have the wesite ready?

Who is going to maintain the Twitter and G+ account?

Maybe we could just re-post the same in all the three accounts.

**Comment by german-e-mas** [comment]
Facebook and Twitter accounts are working, as well as the contact@ekumenlabs.com email. I'll close this issue for cleaning reasons.
