### ISSUE TITLE
Setup email addresses/redirects

### ISSUE THREAD

**Issue by sanbor** [ekumenlabs/ekumenlabs.github.io#8]
TODO: update actual actions
- [ ] create account contact@ekumenlabs.com
- [ ] migrate all existing accounts @creativa77.com to @ekumenlabs.com
- [ ] redirect all existing accounts to @ekumenlabs.com

**Comment by german-e-mas** [comment]
The website has the contact email, and all of them use @ekumenlabs.com. Closing this issue.
