### ISSUE TITLE
Fernando, Andrés and Javier needs a good picture for the team section

### ISSUE THREAD

**Issue by sanbor** [ekumenlabs/ekumenlabs.github.io#9]
We all have a nice picture to put in the about page except @gecofernando who joined Ekumen after the photoshoot. Maybe next Thursday Bea can take a picture of him before the game night.

**Comment by german-e-mas** [comment]
@gecofernando I'm cleaning issues of this repository. I'll close this one because Shok, Andy and you have your pictures alright.
