### ISSUE TITLE
Hide the Blog from the Website

### ISSUE THREAD

**Issue by german-e-mas** [ekumenlabs/ekumenlabs.github.io#94]
Currently, there is a blog entry at www.ekumenlabs.com/blog. There is no direct link to it though.

Prevent the `/blog` folder from being built and deployed.

**Comment by JessicaJackson** [comment]
As we have no plans to regular maintain the blog and have multiple old entries to push, I'm ok with hiding this. Another option is to investigate whether we can have twitter or facebook posts appear in the blog or the other way around that are not related to recruiting.

**Comment by german-e-mas** [comment]
http://www.ekumenlabs.com/blog now gives a 404. Note that we have kept the Blog related files in the source repository, but we are not building them.
