### ISSUE TITLE
Add Emi to the website 

### ISSUE THREAD

**Issue by JessicaJackson** [ekumenlabs/ekumenlabs.github.io#96]
http://www.ekumenlabs.com/team/

Fer to attach photo
Emi to attach text

**Comment by german-e-mas** [comment]
Thanks @JessicaJackson ! I'll be waiting for the photo and text.

**Comment by german-e-mas** [comment]
Emi's bio:

>Emiliano is an Electronics Engineer from the National Technological University - Haedo Regional Faculty. He is passionate about robotics, control and artificial intelligence, and applies his free time to projects related to those topics. He enjoys simulation and making homemade robots such as hexapods or ones using differential-drives.
>
>Besides that, he plays goalie on a local soccer team, enjoys learning new languages, and volunteers time to help the children of Barrio Almafuerte in San Justo, Buenos Aires with their homework and playing games.

**Comment by german-e-mas** [comment]
Merged, built and deployed.
