### ISSUE TITLE
Reorganize the Team page

### ISSUE THREAD

**Issue by JessicaJackson** [ekumenlabs/ekumenlabs.github.io#97]
http://www.ekumenlabs.com/team/

Please move Pato's profile so that it is the first on the page, then Gui's. 

Please create a new section below Fer at the bottom of the page for Advisors (similar to the Meet the Team text style/alignment). In this new section, please put Julian's profile, then Lucas's

**Comment by gecofernando** [comment]
Should we update @tulku and @adamantivm 's profiles to match their new 'advisor' condition?

**Comment by german-e-mas** [comment]
Deployed changes.
