### ISSUE TITLE
Save current job listings

### ISSUE THREAD

**Issue by JessicaJackson** [ekumenlabs/ekumenlabs.github.io#98]
Please save off all the current jobs pages to the website here (or somewhere else of your your choosing as we will be removing / changing some so that only 3 remain):

One place to save them:
https://drive.google.com/drive/folders/0B5QpINXMNER1WnJQbkpUQklPMUE

The 4 job pages that need to be saved are linked from the following page:
http://www.ekumenlabs.com/jobs/

**Comment by german-e-mas** [comment]
@JessicaJackson , I don't have permission to edit the Google Drive's Jobs folder.

Our current `Android developers to work with virtual 3D worlds on mobile devices` job post in the website is almost similar to the `Android Developers for Virtual Worlds` document in the Drive's folder. There are a few tweaks in the "about you" and last sections. What to do in this case? Shall I create a new document for our current job post?

**Comment by german-e-mas** [comment]
The current jobs were saved. I wrote the date they were saved from the website at the end of each doc.

- [Senior developers for robotics projects](https://docs.google.com/document/d/1s6mLg92bvBn_smGCKr1AVAKqYcBQX-SX9YPg8fJzJJc)
- [Web developer for robotics product](https://docs.google.com/document/d/1ufOO27xKMnhHbqT6mGbxoxkHkDa7qOk0zNNwMcToQZQ)
- [Android developers to work with virtual 3D worlds on mobile devices](https://docs.google.com/document/d/1W13jdgs0KVFQk3WsMktB3w16lVZVbkwn5caspFigMjM)
- [Roboticist for simulation project](https://docs.google.com/document/d/1CeIDqdf-SwkexuUdpFdh0hDvOS7n8lk3T5XBbZ1tuqE)

@JessicaJackson , please let me know if you can see them correctly.

**Comment by german-e-mas** [comment]
The jobs were saved on [this Drive's folder](https://drive.google.com/drive/folders/0B5QpINXMNER1WnJQbkpUQklPMUE). Closing this issue.
